### ISSUE TITLE
Cannot run on Big Sur

### ISSUE THREAD

**Issue by MattSquiurrell** [ther0n/UnnaturalScrollWheels#11]
Installed the app this morning by downloading the .dmg as Brew didn't work. When running, I got the message:
"UnnuturalScrollWheels.app" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

However, there was no "open" button to click.

**Comment by ther0n** [comment]
Hi, you need to **right click** on UnnaturalScrollWheels.app and chose "Open". If you simply double click the app you won't see the option to open.

This would be fixed if I pay the $100 a year to join the Apple Developer Program and would also allow me to release on the App Store which I am considering. Until then, anyone using the app will need to put up with that message the first time they run it.

**Comment by MattSquiurrell** [comment]
Having just upgraded to V1.2.0, I can confirm that you have to right-click, choose open, get rid of the warning that tells you it can't be checked, **then right click and choose 'open' again**, at which point you'll have the option to open the app. I know there's little you can do about this as a dev, but hopefully this can help other people.
