### ISSUE TITLE
“UnnaturalScrollWheels” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by jankaWIS** [ther0n/UnnaturalScrollWheels#13]
Hi, your app was working perfectly until two days ago when after reboot it started showing this error:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/54404810/104278242-f36e4700-54b0-11eb-833b-ebcb64d63d12.png">

Any idea what that means and what to do with that?

I installed it on Catalina 10.15.7, now I have Big Sur v11.1.

**Comment by TomasValenta** [comment]
This is duplicate of #12

**Comment by TomasValenta** [comment]
And the solution is described here: https://github.com/ther0n/UnnaturalScrollWheels/issues/12#issuecomment-758095277

**Comment by jankaWIS** [comment]
Oh, I missed that, thanks!
