### ISSUE TITLE
Error on Catalina

### ISSUE THREAD

**Issue by tgrrr** [ther0n/UnnaturalScrollWheels#14]
Big fan. I upgraded, and haven't got it to work since I've upgraded.

Installed with Homebrew

- Mac Catalina 10.15.7
- unnaturalscrollwheels/1.1.0 (779B)

error: `“UnnaturalScrollWheels” will damage your computer. You should move it to the Trash.`

![Screen Shot 2021-01-14 at 11 55 38 am](https://user-images.githubusercontent.com/4689707/104543557-a0d38d00-5660-11eb-9d57-26defa00aeba.png)

**Comment by jrborases** [comment]
Also experiencing problems in last 24h. 

**What happened first:**
App was running in menu bar, but Mac was hanging (badly) when using the scroll wheel on my mouse. It would come back, eventually, sometimes, but the most reliable solution I found was shutting off my mouse and turning it back on.

**What I also tried:**
- Tried with a different mouse that didn't have a power switch, just a cord to the USB input.
- Mac still locked up on scroll, and did eventually unlock, after a good few seconds, but no way to shut mouse on/off.

**Then what I did was:**
- Uninstalled the app by dragging it to Trash.
- Went back to this site and saw the brew version, then tried installing that. Successful. 
- Tried to launch app from Finder, but nothing happened. Did get the warning box eventually about unsigned app (not same box as @tgrrr) but clicked Open. No icon in menu bar. 
- Tried launching it a bunch of times after that from Finder but no box, and no icon in menu bar, and no preferences.

**Now what happens is:**
- No more lockup on scroll, but...
- Scroll wheel behavior is back to vanilla

**Other things to know:**
- My Security & Privacy settings are set as they should be according to the docs, I've double-checked.

---
[*] If this needs to be a separate tik, @ me and I will create it. Thanks for making this app!

**Comment by ther0n** [comment]
@tgrrr
Latest version of the app is [1.1.1](https://github.com/ther0n/UnnaturalScrollWheels/releases/tag/1.1.1). Version 1.1.0 and older won't work anymore since (I think) I screwed up the code signing when releasing 1.1.1.

@jrborases @tgrrr
After updating to 1.1.1 (you may need to do so manually, but [brew should be 1.1.1 now](https://github.com/Homebrew/homebrew-cask/pull/97921)), follow the instructions here: https://github.com/ther0n/UnnaturalScrollWheels/issues/12#issuecomment-758095277

**Comment by jrborases** [comment]
@ther0n the comment in the link solved the problem for me, thank you!
