### ISSUE TITLE
Magic Mouse Trouble

### ISSUE THREAD

**Issue by logankent** [ther0n/UnnaturalScrollWheels#16]
I am having trouble getting the program to work correctly with my magic mouse. I've tried rebooting and all of the invert and detection settings.

**Comment by ther0n** [comment]
I don't have a Magic Mouse to test with but I think it's very likely that the scroll input events sent by the Magic Mouse are the same as the trackpad. When scrolling on mice with scroll wheels scrolling isn't smooth but with a Magic Mouse I believe it's just like scrolling with a trackpad right? If that's the case, the approach UnnaturalScrollWheels takes to invert scrolling won't work unfortunately.

**Comment by benlind** [comment]
This is unfortunate. The competitor Scroll Reverser does support reversing Magic Mice, so I will be using that until this feature is added.
