### ISSUE TITLE
Accept donations [via GitHub]

### ISSUE THREAD

**Issue by jsejcksn** [ther0n/UnnaturalScrollWheels#17]
Hi @ther0n

Not an issue—just a suggestion to check out the GitHub sponsors feature: https://github.com/sponsors

---

Also, you might have intentionally not enabled the [Discussions](https://docs.github.com/en/discussions) feature in this repo, but if that's not the case, you might find it useful for this project. Thanks for sharing your thoughts and work on solving common problems with your community!

**Comment by ther0n** [comment]
Done :)
