### ISSUE TITLE
Definition of "lines" to scroll

### ISSUE THREAD

**Issue by jsejcksn** [ther0n/UnnaturalScrollWheels#18]
Hello @ther0n:

There is an integer input option labelled "Number of lines to scroll per wheel click". This doesn't seem to be any of the following kinds of "lines" in my testing:

- a Finder row item in column view
- a line of text in a browser using default CSS values (`font-size: 16px; line-height: 1.2`)

What is the definition of a "line" for this option? Is is a certain pixel value or does it depend on some kind of context?

_I did [a search in the source for the term `scrollLines`](https://github.com/ther0n/UnnaturalScrollWheels/search?q=scrollLines), but didn't find an answer to my question._

**Comment by ther0n** [comment]
I don't really have an answer for you unfortunately, it's not really something I programmed. The "scrollLines" value is multiplied by `.scrollWheelEventDeltaAxis1` [here](https://github.com/ther0n/UnnaturalScrollWheels/blob/446c263314879f511e4bb7d4d1af7da6ed8ef566/UnnaturalScrollWheels/ScrollInterceptor.swift#L52-L54). I believe `.scrollWheelEventDeltaAxis1` is either 1 or -1 depending on if you scroll up or down, so having a scrollLines setting of 3 will make the `.scrollWheelEventDeltaAxis1` value of the scroll event sent to the application a 3 or -3.

I don't really have a reason describing the value as "lines" other than that's how Windows describes it:
![image](https://user-images.githubusercontent.com/5874301/106841603-70d04600-6670-11eb-9980-999951166404.png)
 It also seems that setting the same value in the app as what you have set in Windows will scroll almost exactly if not exactly the same amount.

**Comment by jsejcksn** [comment]
Ok—I see. Thanks for responding.

Here is a suggestion for consideration: Perhaps the label can be changed to something like "Scroll multiplier" since it is a more literal description of what the option is, and that there aren't really any "lines" involved in the calculation.

Also, it might be nice to provide the default values for the options as hover text or parenthesized inline text or something similar (or maybe a button to revert to the the default values).

Also, in case you're interested, the proper name for a "wheel click" is a scroll [detent](https://en.wikipedia.org/wiki/Detent).

There are definitely pros and cons to using correct technical terms vs (maybe illogical) colloquial language. I have a feeling that your audience trends toward the technical side 😉 .

**Comment by ther0n** [comment]
Thanks for the suggestion! In a future version I might change up the wording a bit. I definitely prefer using the technically correct terms, but I also assume people are familiar with the wording found in Windows as well. Like you said there are advantages to both. I've never heard of a detent and I assume most haven't and although detent is the best word, "wheel click" is self explanatory. I could change the label to "Number of lines to scroll per detent (wheel click)" to make it easy to understand and technically accurate. The larger issue is still the "lines" not actually being lines but "Scroll multiplier per detent (wheel click)" just doesn't sound right to me.

**Comment by jsejcksn** [comment]
Definitely.

> per detent/wheel click

Not all mice wheels have detents, so this only applies to those that do, which is why I suggested not including it at all. (Some mice even have physical mechanisms to disable detent engagement!) If the scroll wheel has detents, then the actions are obviously quantized to that degree of radial movement, and if not, then the multiplication factor applies to however often the sensor polls, etc.
