### ISSUE TITLE
Disable mouse acceleration setting persists even after app is quit

### ISSUE THREAD

**Issue by jsejcksn** [ther0n/UnnaturalScrollWheels#22]
**Version:** `1.2.2 (189)`

**Expected:**
After Quitting UnnaturalScrollWheels, tracking acceleration will be enabled for mouse input.

**Observed:**
After Quitting UnnaturalScrollWheels, the tracking acceleration setting in the app preferences persists.

I'm not really sure how this is possible since—based on the description in the readme—the app only works in an active way by intercepting and modifying events. Does the app actually modify any user or system preferences?

**Comment by ther0n** [comment]
I based the code for disabling mouse acceleration off of [this](https://github.com/apsun/NoMouseAccel#technical-notes) which takes advantage of a possible bug, rather than intercepting input events like the scroll inversion does.

It doesn't actually modify any values permanently so logging out and back in will revert back to no mouse acceleration until the app is opened again.

**Comment by jsejcksn** [comment]
> I based the code for disabling mouse acceleration off of [this](https://github.com/apsun/NoMouseAccel#technical-notes) which takes advantage of a possible bug, rather than intercepting input events like the scroll inversion does.

Interesting... I wonder if it's an oversight or actually designed that way. 🤔

> It doesn't actually modify any values permanently so logging out and back in will revert back to no mouse acceleration until the app is opened again.

I was seeing that as well in testing. Since everything has to be unloaded from memory during logout, it's a rather disruptive process to revert. The only current alternative is to navigate to the options menu and disable it before quitting (which also requires manually re-enabling if one uses that setting—which is slightly less disruptive, but equally annoying 😤).

**Perhaps the app can restore the unmodified value upon quitting rather than leaving it persisted.** I know very little about the macOS app development process—otherwise I'd send a PR.

---

Contextually-related (more just sharing my thoughts publicly): I wonder if there's a way to create menu bar boolean toggles (like this one for bluetooth):

<img width="297" alt="Screen Shot 2021-02-05 at 17 19 30" src="https://user-images.githubusercontent.com/868251/107099390-24534a80-67d7-11eb-9d41-1324ec544564.png">

**Comment by ther0n** [comment]
Fixed by [8cedd22](https://github.com/ther0n/UnnaturalScrollWheels/commit/8cedd22f80260e904582e84145a7da9afc4e0757). Will be included in the next release.
