### ISSUE TITLE
GUI Easy But, Wording is confusing

### ISSUE THREAD

**Issue by jredfox** [ther0n/UnnaturalScrollWheels#23]
most of the settings do not explain what they do nor does your GitHub readme. For example the disabling of the acceleration seems to make things go faster not slower. it's not really an issue with the program but, an issue on what the program does. 

that being said I love the app and idk why Mac hasn't fixed the bug yet nor why the other options are not in default macOS that was in your app

**Comment by ther0n** [comment]
Yeah it would probably be good to add some more detailed explanations in the readme. The short explanations use the most commonly used terms I know of for each option that will fit in the GUI.

As far as the acceleration options:

Mouse acceleration is most commonly disabled when you want to play certain games that require accuracy, although I like having it disabled at all times so I can use my mouse quickly and accurately. Say you move your mouse 1 inch on your mouse pad over the course of 5 seconds, with macOS defaults (mouse acceleration on) the cursor won't move very far on the screen. If you again move your mouse 1 inch but this time do it quickly, the cursor will move a lot further. If you check the "Disable mouse acceleration" option, moving your mouse 1 inch on the mouse pad will always move the cursor the same amount regardless of how quickly you move the mouse over that inch. In some cases, like moving your mouse slowly the cursor will move more which might make it seem "faster" which is likely what you experienced. Other cases like moving your mouse super fast, the cursor will move less on the screen than it would have if you had mouse acceleration on which would make the mouse feel "slower". When mouse acceleration is disabled, the distance your cursor travels when the mouse is moved a fixed distance is controlled by your mouses DPI (I have my mice set to 800). [Here's a video that may explain it better than I can.](https://www.youtube.com/watch?v=16diwK6HWbI)

The "Disable scroll acceleration" option is similar to "Disable mouse acceleration" except that it applies to the scroll wheel. With the option off (macOS defaults), scroll faster the content will scroll more for each click than if you scroll the same amount but slower. The simplest way I can think of to explain it is that when it's enabled, scrolling the wheel a certain amount will always scroll the content by the same amount regardless of how quickly you scroll the wheel. The "number of lines to scroll per wheel click" option defines how much the content should scroll for each mouse click. This is modeled after the [Mouse Properties menu in Windows](https://user-images.githubusercontent.com/5874301/106841603-70d04600-6670-11eb-9980-999951166404.png) which many people are likely familiar with. One thing that may be confusing is that "lines" doesn't refer to lines of text, a "line" would just be how ever much is scrolled if the option is set to "1".
