### ISSUE TITLE
No longer runs - EXC_BAD_ACCESS crash on start - M1 Mac Mini / 11.5

### ISSUE THREAD

**Issue by luckman212** [ther0n/UnnaturalScrollWheels#25]
Hey @ther0n - thanks for this project and I had been using it successfully for a year or so on my previous Mac (Intel Mac Mini 2018 / Big Sur 11.5). But, yesterday I got a new M1 Mac and now I can't get it to run anymore. I zipped up a bunch of crash reports (attached below) ... they all look the same: `EXC_BAD_ACCESS / KERN_INVALID_ADDRESS at 0x0000000000000008`

Tried deleting the prefs plist, rebooting etc. Just can't get it to run 🙁
Sorry I can't be more helpful on debugging.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2847]
```

💾 [UnnaturalScrollWheels_crashes.zip](https://github.com/ther0n/UnnaturalScrollWheels/files/6872912/UnnaturalScrollWheels_crashes.zip)

**Comment by ther0n** [comment]
Try going to Security & Privacy > Privacy > Accessibility > Click the lock to make changes. Then find "UnnaturalScrollWheels.app" from the list and click the "-" to remove it from the list. Completely uninstall the app and delete the prefs plist as you did before. Then download the latest version or install fresh from homebrew, hopefully that should get it running again.

**Comment by luckman212** [comment]
Hmm! That worked! I guess it would be "nice" if the app popped up a little dialog when it fails to get the permissions instead of just crashing silently, but - glad to have it back again. Thank you

**Comment by ther0n** [comment]
Currently the app checks if it has the necessary permissions and if it doesn't it _should_ pop up a message. As far as I know I'm using those APIs as Apple intended but sometimes things get borked like that. I did run into this issue in development a while back though which is why I knew the fix. I think it's actually a bug with macOS itself but I'm not completely sure and I'm not knowledgeable enough to figure that out unfortunately.
