### ISSUE TITLE
Doesn't Open on macOS Big Sur 11.5.1

### ISSUE THREAD

**Issue by AdinAck** [ther0n/UnnaturalScrollWheels#26]
I just updated to Big Sur 11.5.1 and now UnnaturalScrollWheels.app does nothing with I open it.
No GUI appears, the settings don't apply, seems to just crash on run, although no error message displays.

**Comment by AdinAck** [comment]
Update: After running it by dragging the executable into a terminal window, it seems to have "worked", my scroll directions are now reversed, but the GUI will not display so I can't make any changes, although luckily I don't want to make any changes. Hopefully this will carry over when I restart.

**Comment by ther0n** [comment]
You might be having the same issue as #25. If you are having problems try the solution [here](https://github.com/ther0n/UnnaturalScrollWheels/issues/25#issuecomment-894701883).
