### ISSUE TITLE
UnnaturalScrollWheels can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by aHagouel** [ther0n/UnnaturalScrollWheels#27]
When trying to run after brew install. Running MacOS 11.5.2 on M1 chip. "This software needs to be updated. Contact the developer for more information."

**Comment by ther0n** [comment]
The app doesn't need to be updated. Apple decided that this message should appear for any application that isn't notarized, which would cost me100$ a year as a developer account is required. To open the app follow the instruction steps 2 and 3 in the ["Manual Download" section of the readme.](https://github.com/ther0n/UnnaturalScrollWheels#manual-download) Once I reach $100/year in donations for the app I will join the developer program to get the application notarized, however the app works fine without this :).

**Comment by ZairMahmood** [comment]
If you had it previously installed, you need to remove the old `UnaturalScrollWheels` from the Privacy section and re-add it. Might wanna add this info somewhere @ther0n
