### ISSUE TITLE
Stopped working after update to 11.5.2

### ISSUE THREAD

**Issue by ct-taylor** [ther0n/UnnaturalScrollWheels#32]
The app no longer launches after update. I have reinstalled both from dmg and homebrew, verified the Accessibility settings are enabled, have right-clicked opened repeatedly, it appears to open but the taskbar app never appears and my scrollwheel functions as usual (i.e, it's unusable for me!)

Let me know if there's anything I can do to help troubleshoot.

**Comment by Logic1-LM** [comment]
I have the same issue with 12.0.1 on new 14" MBP.
I miss this app.
Happy to assist if needed.

**Comment by ther0n** [comment]
This might be the same as issue #26 and #25. Try the troubleshooting steps [here](https://github.com/ther0n/UnnaturalScrollWheels/issues/25#issuecomment-894701883).

**Comment by Logic1-LM** [comment]
> This might be the same as issue #26 and #25. Try the troubleshooting steps [here](https://github.com/ther0n/UnnaturalScrollWheels/issues/25#issuecomment-894701883).

Thank you, issues resolved. Great utility.

**Comment by geek3** [comment]
Installation works for me for v1.2.2 (189) on MBP2021 Monterey via brew.
