### ISSUE TITLE
Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by TysonMN** [ther0n/UnnaturalScrollWheels#33]
After installing via Homebrew, I can't open it because Apple cannot check it for malicious software.

> “UnnaturalScrollWheels” can’t be opened because Apple cannot check it for malicious software.
>
> This software needs to be updated. Contact the developer for more information.
>
> Homebrew Cask downloaded this file today at 2:45 PM from github.com.

<img width="273" alt="Screen Shot 2021-11-09 at 3 01 50 PM" src="https://user-images.githubusercontent.com/34664007/141004046-512f9817-5fa6-4757-a0f8-93f22e70cf28.png">

**Comment by Logic1-LM** [comment]
I had the same, right click on app in app folder and select Open.

**Comment by TysonMN** [comment]
Yes, that worked.  Thanks!
