### ISSUE TITLE
App not working on macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by wulfland** [ther0n/UnnaturalScrollWheels#34]
I installed the app from homebrew - but when I launch it it I see the following dialog:

> “UnnaturalScrollWheels” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

**Comment by matonse** [comment]
You can go into your apps folder, hold control and click open to bypass this security verification.
Other than that the app works fine for me (MacOS Monterey 12.0.1)

**Comment by wulfland** [comment]
Great! It works. Thanks 👍
