### ISSUE TITLE
Vertical scrolling isn't inverted, app prompts for Accessibility permission but already has it

### ISSUE THREAD

**Issue by Sverigevader** [ther0n/UnnaturalScrollWheels#47]
Disclaimer: This is my first GH issue, sorry if I'm breaking any rules here.

## Problem
Vertical scroll is not inverted and the app prompts for permission every time I start it or try to access its preferences:
![Screenshot 2022-05-07 at 12 27 18](https://user-images.githubusercontent.com/1084623/167250501-78a22f48-b527-4c11-9cab-483b87e9cbe6.png)
![Screenshot 2022-05-07 at 12 27 27](https://user-images.githubusercontent.com/1084623/167250525-704c354a-a098-4e1b-a632-4ed3b36890a2.png)

The app already has the permissions it needs: 
![Screenshot 2022-05-07 at 12 27 38](https://user-images.githubusercontent.com/1084623/167250533-87f95e6a-a698-40ce-a08d-563af75b7121.png)

I can't open the app settings without getting prompted for the Accessibility permissions. Repeatedly opening the app through spotlight and pressing cancel on the permissions prompt takes me to the settings, where inverted scroll is active, but doesn't change anything when cycling on/off

## Things that work

* Mouse acceleration is disabled
* Scroll acceleration is disabled

## Things I've tried

* Removing and giving it permission again didn't help.
* I tried uninstalling and reinstalling but it doesn't help.
* Uninstalling with brew and installing manually removing the permission in between didn't work

**Comment by bravo2day** [comment]
Same issue here. 12.4 (21F79)

**Comment by sereyn** [comment]
Same issue.

Versions:
- UnnaturalScrollWheels: 1.2.3 (192)
- macOS: 12.4 (M1 chip)

**Comment by thexixx** [comment]
I solved the same problem by removing the app from 'Accessibility' settings and put it back.

**Comment by Sverigevader** [comment]
> I solved the same problem by removing the app from 'Accessibility' settings and put it back.

Wow this seems to have fixed it!
