### ISSUE TITLE
Run at login button not working

### ISSUE THREAD

**Issue by fuomag9** [ther0n/UnnaturalScrollWheels#51]
When installing from homebrew via `brew install --cask unnaturalscrollwheels` and clicking on the `Run at login` feature on the panel, a page to https://github.com/ther0n/UnnaturalScrollWheels/blob/master/RunAtLogin.md will open and it's a 404 not found.

[Searching for the file on the repository](https://github.com/ther0n/UnnaturalScrollWheels/search?q=RunAtLogin) yields nothing, how do I enable run at login? Is it even implemented?

**Comment by ther0n** [comment]
Oops, the most recent commit to master implemented an automatic Run at Login feature and removed the documentation to do it manually. I originally wrote this app for my own use and that was an easy way to add documentation to the app with little code. OS has launch at login built so I could just tell people how to use the app.

For now though here's a link to the file when it was still present in the repo:
https://github.com/ther0n/UnnaturalScrollWheels/blob/ddfc7ecbfa88c2d657b9a4fa5dddd2f9c01ae221/RunAtLogin.md

And this was the contents:

# Run at login

To run the application at login, add it to you login items:

1. Open System Preferences > Users & Groups then select the "Login Items" tab

2. Add "UnnaturalScrollWheels.app" to the Login Items list either by dragging and dropping the application into the window, or by clicking the "+" and selecting the app.

<img width="460" alt="LoginItems" src="https://user-images.githubusercontent.com/5874301/177018552-c120f7b2-c109-4d62-8410-4b54120adda0.png">

**Comment by fuomag9** [comment]
> Oops, the most recent commit to master implemented an automatic Run at Login feature and removed the documentation to do it manually. I originally wrote this app for my own use and that was an easy way to add documentation to the app with little code. OS has launch at login built so I could just tell people how to use the app.
> 
> For now though here's a link to the file when it was still present in the repo: https://github.com/ther0n/UnnaturalScrollWheels/blob/ddfc7ecbfa88c2d657b9a4fa5dddd2f9c01ae221/RunAtLogin.md
> 
> And this was the contents:
> 
> # Run at login
> To run the application at login, add it to you login items:
> 
> 1. Open System Preferences > Users & Groups then select the "Login Items" tab
> 2. Add "UnnaturalScrollWheels.app" to the Login Items list either by dragging and dropping the application into the window, or by clicking the "+" and selecting the app.
> 
> <img alt="LoginItems" width="460" src="https://user-images.githubusercontent.com/5874301/177018552-c120f7b2-c109-4d62-8410-4b54120adda0.png">

fyi if the latest commit is already present on homebrew I did not find the app in the auto login section (I added it manually), thanks for the fast debugging :)

**Comment by ther0n** [comment]
Yeah, the master branch has the feature implemented but I haven't released a new version yet so it's not on the releases page or homebrew. Guess my little hack to save me some work is coming back to bite :). I will try to get to doing that when I get a chance.

**Comment by ther0n** [comment]
Fixed by the latest release

**Comment by SukkaW** [comment]
@ther0n Would you mind updating the homebrew cask as well? I installed the `UnnaturalScrollWheels` from homebrew and encountered the same issue. I notice the issue has been fixed in 1.3.0 but the homebrew cask still has 1.2.3.
