### ISSUE TITLE
Stopped working on 12.6

### ISSUE THREAD

**Issue by rverr** [ther0n/UnnaturalScrollWheels#64]
I upgraded to 12.6 (21G115) recently and found no way to get the application to work again.
The application seems to be running as normal, but the functionality is gone.
I tried completely uninstalling (incl. removing the permissions) and installing fresh, but to no avail.

**Comment by pdewas** [comment]
Same here

**Comment by vinayagg** [comment]
Thank you, that helped me figure out why my mouse keeps changing direction (it is because laptop sleeps)

**Comment by JFizDaWiz** [comment]
currently on 
12.6 (21G115) 
Mac Studio (2022)

I use this application solely to disable mouse acceleration and whenever the mac goes to sleep and wakes back up my mouse is really slow (acceleration reenabled)

The application is running still, I click on the icon in the menu bar, go to Preferences and immediately click OK without changing any settings and acceleration is working again.

**Comment by rverr** [comment]
Solved by uninstalling, removing permission - restarting(!) - and then installing again.

**Comment by dgolant** [comment]
Every time my machine restarts I need to uninstall via brew and install again. I think maybe something with the security/privacy check from macos is getting messed up
