### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by slu1982** [ther0n/UnnaturalScrollWheels#9]
Hey,

love UnnaturalScrollWheels. Does exactly what MacOS should have as a native functionality.

Would be great if we can get a Universal build with Apple Silicon support.

Thanks.

Best,
Sebastian

**Comment by ther0n** [comment]
Done!
https://github.com/ther0n/UnnaturalScrollWheels/releases/tag/1.1.1

**Comment by slu1982** [comment]
Much appreciated!
